// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqgjgmjonhwfdxwtsswu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxZ2pnbWpvbmh3ZmR4d3Rzc3d1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MTMzNTIsImV4cCI6MjA2MjE4OTM1Mn0.EDLUVr_zlQ1CbyiE5Dgxp2rK5ZQKQs8qGYG-cA5KwOM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);